#! /usr/bin/env python3
##########################################################################
# pysphinxdoc - Copyright (C) AGrigis, 2026
# Distributed under the terms of the CeCILL-B license, as published by
# the CEA-CNRS-INRIA. Refer to the LICENSE file or to
# http://www.cecill.info/licences/Licence_CeCILL-B_V1-en.html
# for details.
##########################################################################


import fire
from pysphinxdoc.interface import generate_documentation


if __name__ == "__main__":
    fire.Fire(generate_documentation)
